//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment6CSE445
{


    public partial class Member
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtRegUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegUsername;

        /// <summary>
        /// txtRegPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegPassword;

        /// <summary>
        /// txtRegConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegConfirmPassword;

        /// <summary>
        /// txtRegCaptcha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegCaptcha;

        /// <summary>
        /// lblCaptcha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCaptcha;

        /// <summary>
        /// imgCaptcha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCaptcha;

        /// <summary>
        /// btnReloadCaptcha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReloadCaptcha;

        /// <summary>
        /// btnRegister control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRegister;

        /// <summary>
        /// txtLoginUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLoginUsername;

        /// <summary>
        /// txtLoginPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;

        /// <summary>
        /// btnLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
